name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: 
      group: ci-${{github.workflow}}-${{github.ref}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Node
        uses: actions/setup-node@v1
        with: 
          node-version: '16'
      
      - name: Install
        run: |
          npm install
          npm ci
          npm run build